model_list:
  - model_name: secretary-model
    litellm_params:
      model: mistral/mistral-small-latest
      api_key: os.environ/MISTRAL_API_KEY

router_settings:
  routing_strategy: usage-based-routing-v2
  num_retries: 1

litellm_settings:
  drop_params: true
